#!/usr/bin/env bash
# Displays
## The content of the current directory
## In a list format
## Where only the part of the name after the first dash is displayed

for filename in *
do
    echo "$filename" | cut -d "-" --fields=2
done
